input {
  udp {
    port => 5044
    codec => json {
      target => "payload"
    }
  }
}

filter {
  if [payload][logger_name] {
    mutate {
      add_field => { "service_name" => "%{[payload][logger_name]}" }
    }
  }
}

output {
  stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-%{+YYYY.MM}"
  }
}