input {
  udp {
    port => 5044
    codec => json {
      target => "payload"
    }
  }
}

filter {
  if [payload][message] {
    mutate {
      replace => { "message" => "%{[payload][message]}" }
    }
  }

  if [payload][level] {
    mutate {
      add_field => { "level" => "%{[payload][level]}" }
    }
  }

  if [payload][logger_name] {
    mutate {
      add_field => { "logger_name" => "%{[payload][logger_name]}" }
    }
  }

  if [payload][service] and [payload][service] != "" {
    mutate {
      add_field => {
        "service" => "%{[payload][service]}"
        "[@metadata][target_service]" => "%{[payload][service]}"
      }
    }
  } else if [payload][logger_name] =~ /^auth/ {
    mutate {
      add_field => {
        "service" => "auth_app"
        "[@metadata][target_service]" => "auth_app"
      }
    }
  } else if [payload][logger_name] =~ /^ugc_api/ {
    mutate {
      add_field => {
        "service" => "ugc_api_app"
        "[@metadata][target_service]" => "ugc_api_app"
      }
    }
  } else if [payload][logger_name] =~ /^ugc_etl/ {
    mutate {
      add_field => {
        "service" => "ugc_etl_app"
        "[@metadata][target_service]" => "ugc_etl_app"
      }
    }
  } else {
    mutate {
      add_field => {
        "service" => "app"
        "[@metadata][target_service]" => "app"
      }
    }
  }
}

output {
  stdout {
    codec => rubydebug
  }

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_service]}-%{+YYYY.MM.dd}"
  }
}
